language: java

## https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx


jdk:
  - oraclejdk8

# http://stackoverflow.com/questions/35128777/travis-ci-build-failed#comment58070003_35153221
before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean install
  - ./gradlew check

branches:
  only:
  - master

notifications:
  email: false
